const categories = [
  {
    code: "concept-art",
    name: "Concept Art",
    bannerImg: "1Z6monK1LG5i-6pW7UsxCP2IZE0mkFkAP",
    imgs: [
      "1Z6monK1LG5i-6pW7UsxCP2IZE0mkFkAP",
      "1Vez69pjIurPhzRgEI4UzuIJhihUIkyDn",
      "1XpfumJd7mOBNezw7zT3TGMAdE3FmjJst",
      "1XPgIkb_fr8Gh1ack_cqGx68S35n4N8dV",
      "1QyWUjqtFMPzy49nPuqrgbiNgM8WjMEiC",
      "1OGlsCwgriJKW_l5dXK9lSiHkh17TRHnc",
      "1jsp-cfJ5RyF-f1B4I7J_f7DjC8WBWgCT",
      "1RkxEDeH5kaWkZlhcR9TNdRfQlfTk4MIV",
      "1JkVKFbIPs3CjXUVqk58nivulBq0SnCME",
      "1WcU6DS35HYmgyeunyHVufKnghPwr6_OF",
      "1ago-DNWHVuYWPm0RnwMG4co3pwlC9hsa",
      "1vVAUAS7eN9dfWqJY_XPIkkqDnYS23YM2",
      "1CWPuIm0B0q-DEYCGD1g5LItcbJ0jKBdV",
      "1jqTboFJHJVZlDqaRGTwV5nQj7d28AWxk",
      "1LrKfG88GunKQFNUdTlUUlzHc993o8W1T",
      "10m6Rdl64jugWs7femktlj3cc6vHlWxYE",
      "1mvQh7ALodZX4zs5B-oT62l8KPo93AFhQ",
      "1wfanH9g_koQkCOukk1sUWz5CljeSVjIG",
      "11by8sFDv5gYpwZe_vEth0vDTm23BWqeV",
      "1q9s8o4r5M_PzpQsH-h1P3vy8pmYu70u3",
      "1krpWjwcKmZQb5jJkkE3aAxyooQMF51hP",
      "1TxeswqAM0Rqvh6z_pobdj_l1kDOF7rst",
      "1j3QPpt-uIduXIVdiHiqxJXo5UsL0xnW5",
      "1ioCcgRpdZU1gy1M8B_C6YA6zhIoDRnO2",
      "1zUAfBleAz6_VfJ2_CKsfmoibvoQPD8NW",
      "10XmrNhzLp85oiAog29S8o1VnE10IWDzU",
      "19w37NQ2IJ73czhPvEH9I68rdSmmCuKgW",
      "1BSo0ig5d-dFMUdlgmOS0vyQ8_KcORwlY",
      "1ppZP1bsDBF3ta-nSMlo7nL7sWiSdkAS5",
      "1bUHAqKGKgv2dRIGC8J4poF9mj6ef692b"
    ],
  },
  {
    code: "illustration",
    name: "Illustration",
    bannerImg: require("@/assets/images/illustration/illustration-1.png"),
    imgs: [require("@/assets/images/illustration/illustration-1.png")],
  },
  {
    code: "ux-ui-game",
    name: "UX-UI Game",
    bannerImg: require("@/assets/images/ux-ui/ux-ui-1.png"),
    imgs: [require("@/assets/images/ux-ui/ux-ui-1.png")],
  },
  {
    code: "hand-drawing",
    name: "Hand Drawing",
    bannerImg: require("@/assets/images/hand-drawing/hand-drawing-1.png"),
    imgs: [require("@/assets/images/hand-drawing/hand-drawing-1.png")],
  },
  {
    code: "doodle",
    name: "Doodle",
    bannerImg: require("@/assets/images/doodle/doodle-1.png"),
    imgs: [require("@/assets/images/doodle/doodle-1.png")],
  },
];

export { categories };
